# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e19dfcf39ab07445aa1e91b0773f272982c223145e7d4af5d4e639c976115571708651319b0c8fc310e2745b713610c2c04e20fdc28a3b18b09482ba119c292

test:
  secret_key_base: a6d431764e5b9fe2181f9c65b774db5b316550b6db3454b809250faff2050d8af62bfbc27d8bb7b33fe3c405c9fee6a356fafd0f9b18c176757e970dabcd8b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
